/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lesInterfacesGraphiques;

import java.awt.Color;
import javax.swing.JOptionPane;
import lesClassesMetiers.AccessBD;
import lesClassesMetiers.Utilisateur;
import java.util.Date;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import lesClassesMetiers.ConsulterSms;
import lesClassesMetiers.Membre;





/**
 *
 * @author PC
 */
public class Administrateur extends Application{

    /**
     * Creates new form Administrateur
     */
    
    static AccessBD  access = new AccessBD();
   
    public Administrateur() {
        initComponents();
      
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton23 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton21 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();

        setTitle("Administrateur");
        setLocation(new java.awt.Point(100, 5));
        setMinimumSize(new java.awt.Dimension(1190, 690));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(51, 51, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Gestion des flux financiers ");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(520, 10, 270, 60);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 10, 1170, 90);

        jPanel3.setBackground(new java.awt.Color(102, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\LPTI 3 DAR\\S5\\JAVA_EE_SOA\\lesTPJavaEE\\GestionDesFlusFinanciers\\images\\fermer.png")); // NOI18N
        jButton1.setText("Déconnexion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(10, 440, 190, 50);
        jButton1.getAccessibleContext().setAccessibleName("Annuler");

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\LPTI 3 DAR\\S5\\JAVA_EE_SOA\\lesTPJavaEE\\GestionDesFlusFinanciers\\images\\nouveau.png")); // NOI18N
        jButton2.setLabel("Créer un Utilisateur");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(10, 10, 190, 50);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\LPTI 3 DAR\\S5\\JAVA_EE_SOA\\lesTPJavaEE\\GestionDesFlusFinanciers\\images\\utilisateur-icone-5739-32.png")); // NOI18N
        jButton3.setText("Utilisateurs");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(10, 90, 190, 50);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\LPTI 3 DAR\\S5\\JAVA_EE_SOA\\lesTPJavaEE\\GestionDesFlusFinanciers\\images\\nouveau.png")); // NOI18N
        jButton4.setLabel("Créer un membre");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);
        jButton4.setBounds(10, 180, 190, 50);

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\LPTI 3 DAR\\S5\\JAVA_EE_SOA\\lesTPJavaEE\\GestionDesFlusFinanciers\\images\\m (2).png")); // NOI18N
        jButton5.setText(" membres");
        jButton5.setActionCommand("membre");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);
        jButton5.setBounds(10, 270, 190, 50);

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\LPTI 3 DAR\\S5\\JAVA_EE_SOA\\lesTPJavaEE\\GestionDesFlusFinanciers\\images\\Cash-register-icon.png")); // NOI18N
        jButton7.setLabel("Gérer la Finance");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7);
        jButton7.setBounds(10, 360, 190, 50);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 110, 210, 530);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new java.awt.CardLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(null);

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel30.setText("Créer un nouvel utilisateur ");
        jPanel5.add(jLabel30);
        jLabel30.setBounds(380, 20, 230, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Mot de passe :");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(260, 270, 90, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrateur", "Financier" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBox2);
        jComboBox2.setBounds(400, 110, 190, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Id  :");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(260, 110, 30, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Login :");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(300, 190, 50, 30);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField3);
        jTextField3.setBounds(400, 190, 190, 30);

        jButton16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton16.setText("Ajouter");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton16);
        jButton16.setBounds(420, 390, 110, 40);

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel5.add(jPasswordField1);
        jPasswordField1.setBounds(400, 270, 190, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Grade :");
        jPanel5.add(jLabel14);
        jLabel14.setBounds(300, 110, 60, 30);

        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField4);
        jTextField4.setBounds(400, 110, 190, 30);

        jPanel4.add(jPanel5, "card2");

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.setLayout(null);

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel31.setText("Créer un nouvel utilisateur ");
        jPanel9.add(jLabel31);
        jLabel31.setBounds(380, 20, 230, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Mot de passe :");
        jPanel9.add(jLabel13);
        jLabel13.setBounds(260, 270, 90, 30);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrateur", "Financier" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel9.add(jComboBox3);
        jComboBox3.setBounds(400, 110, 190, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Id  :");
        jPanel9.add(jLabel15);
        jLabel15.setBounds(260, 110, 30, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Login :");
        jPanel9.add(jLabel16);
        jLabel16.setBounds(300, 190, 50, 30);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel9.add(jTextField5);
        jTextField5.setBounds(400, 190, 190, 30);

        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        jPanel9.add(jPasswordField2);
        jPasswordField2.setBounds(400, 270, 190, 30);

        jButton23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton23.setText("Modifier");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton23);
        jButton23.setBounds(420, 390, 120, 40);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Grade :");
        jPanel9.add(jLabel17);
        jLabel17.setBounds(300, 110, 60, 30);

        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel9.add(jTextField6);
        jTextField6.setBounds(400, 110, 190, 30);

        jPanel4.add(jPanel9, "card2");

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Modifier un Utilisateur");
        jPanel6.add(jLabel2);
        jLabel2.setBounds(370, 20, 190, 30);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Login", "mot de passe", "Grade", "N°"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel6.add(jScrollPane1);
        jScrollPane1.setBounds(20, 80, 910, 290);

        jButton17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton17.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\LPTI 3 DAR\\S5\\JAVA_EE_SOA\\lesTPJavaEE\\GestionDesFlusFinanciers\\images\\supprimer.png")); // NOI18N
        jButton17.setText("Supprimer");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton17);
        jButton17.setBounds(560, 390, 170, 40);

        jButton18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton18.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\LPTI 3 DAR\\S5\\JAVA_EE_SOA\\lesTPJavaEE\\GestionDesFlusFinanciers\\images\\modifier.png")); // NOI18N
        jButton18.setText("Modifier");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton18);
        jButton18.setBounds(140, 390, 170, 40);

        jPanel4.add(jPanel6, "card3");

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Créer un membre ");
        jPanel7.add(jLabel3);
        jLabel3.setBounds(440, 20, 150, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Adresse :");
        jPanel7.add(jLabel8);
        jLabel8.setBounds(200, 330, 60, 50);
        jPanel7.add(jTextField12);
        jTextField12.setBounds(330, 340, 200, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Nom :");
        jPanel7.add(jLabel9);
        jLabel9.setBounds(220, 90, 50, 30);
        jPanel7.add(jTextField13);
        jTextField13.setBounds(330, 90, 200, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Prenom :");
        jPanel7.add(jLabel10);
        jLabel10.setBounds(200, 150, 70, 30);
        jPanel7.add(jTextField14);
        jTextField14.setBounds(330, 150, 200, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Date de naissance :");
        jPanel7.add(jLabel11);
        jLabel11.setBounds(140, 210, 120, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Date entrée :");
        jPanel7.add(jLabel12);
        jLabel12.setBounds(180, 270, 90, 30);

        jButton19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton19.setText("Valider");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton19);
        jButton19.setBounds(370, 430, 120, 40);
        jPanel7.add(jDateChooser1);
        jDateChooser1.setBounds(330, 270, 200, 30);
        jPanel7.add(jDateChooser2);
        jDateChooser2.setBounds(330, 210, 200, 30);

        jPanel4.add(jPanel7, "card4");

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Activer / Désactiver un membre");
        jPanel8.add(jLabel4);
        jLabel4.setBounds(400, 20, 250, 30);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Titre 1", "Titre 2", "Titre 3", "Titre 4", "Titre 5", "Titre 6"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel8.add(jScrollPane2);
        jScrollPane2.setBounds(20, 100, 910, 180);

        jButton21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton21.setText("Activer");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton21);
        jButton21.setBounds(300, 420, 140, 40);

        jButton24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton24.setText("Désactiver");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton24);
        jButton24.setBounds(510, 420, 140, 40);

        jPanel4.add(jPanel8, "card5");

        jPanel1.add(jPanel4);
        jPanel4.setBounds(230, 110, 950, 530);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1190, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jPanel4.removeAll();
        jPanel4.repaint();
        jPanel4.revalidate();

        jPanel4.add(jPanel5);
        jPanel4.repaint();
        jPanel4.revalidate();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jPanel4.removeAll();
        jPanel4.repaint();
        jPanel4.revalidate();

        jPanel4.add(jPanel6);
        jPanel4.repaint();
        jPanel4.revalidate();
        
                 
           
         
         
        int listes = jComboBox2.getSelectedIndex();

        switch(listes)  {

            case 0 :
                
                 DefaultTableModel dftm=new javax.swing.table.DefaultTableModel(
            new Object [][] {
                 
            },
            new String [] {
                "Grade", "Login", "Mot de passe","Id"
            }
        );
         
         dftm = Utilisateur.lesAdmin(dftm);
         jTable1.setModel(dftm); 
  
            break;

            case 1 :
                
                 DefaultTableModel dftmf=new javax.swing.table.DefaultTableModel(
            new Object [][] {
                 
            },
            new String [] {
                "Grade", "Login", "Mot de passe","Id"
            }
        );
   
         dftm = Utilisateur.lesFinanciers(dftmf);
         jTable1.setModel(dftm);

            break;
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jPanel4.removeAll();
        jPanel4.repaint();
        jPanel4.revalidate();

        jPanel4.add(jPanel8);
        jPanel4.repaint();
        jPanel4.revalidate();
        
         DefaultTableModel dftm=new javax.swing.table.DefaultTableModel(
            new Object [][] {
                 
            },
            new String [] {
               "Numéro","Nom ", "Prenom", "Date de Naissance","Date d'Entrée","Adresse","Etat"
            }
        );
        
         dftm = Membre.lesMembres(dftm);
         jTable2.setModel(dftm);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
       FinancierAdmin financiers = new FinancierAdmin();
      financiers.setVisible(true);
      this.hide();
      
      if (ConsulterSms.controle()==1){
        financiers.jButton16.setBackground(Color.gray);
     }else  
          financiers.jButton16.setBackground(Color.green);
         
    
      
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.hide();
         Accueil accueil = new Accueil();
         accueil.setVisible(true); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jPanel4.removeAll();
        jPanel4.repaint();
        jPanel4.revalidate();

        jPanel4.add(jPanel7);
        jPanel4.repaint();
        jPanel4.revalidate();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        
       try{
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            int ligne = jTable1.getSelectedRow();
            String table = (jTable1.getModel().getValueAt(ligne, 3).toString());
            //int y = Integer.parseInt(table_click);
            int i = JOptionPane.showConfirmDialog(null,"Voulez-vous supprimer cet Utilisateur ?", "Supprimer", JOptionPane.YES_NO_OPTION);
            switch(i){
               case 0 :
                        model.removeRow(ligne);
                        Utilisateur.supprimerAdmin(table); 
                        JOptionPane.showMessageDialog(null, "Supprimé avec succès");
                        break;
               case 1 : break;
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e, "Erreur", JOptionPane.ERROR_MESSAGE);
 }
        
        
        
        
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        
          
                DefaultTableModel modele = (DefaultTableModel) jTable1.getModel();
                int ligne = jTable1.getSelectedRow();
                String grade = (jTable1.getModel().getValueAt(ligne, 0).toString());
                String login = (jTable1.getModel().getValueAt(ligne, 1).toString());
                String mdp = (jTable1.getModel().getValueAt(ligne, 2).toString());
                String id_user = (jTable1.getModel().getValueAt(ligne, 3).toString());
                
                
                
                int i = JOptionPane.showConfirmDialog(null,"Voulez-vous modifier cet utilisateur ?", "Modifier", JOptionPane.YES_NO_OPTION);
                switch(i){
                   case 0 :
                             jPanel4.removeAll();
                             jPanel4.repaint();
                             jPanel4.revalidate();

                             jPanel4.add(jPanel9);
                             jPanel4.repaint();
                             jPanel4.revalidate();
                             
                            jTextField6.setText(id_user);
                            jComboBox3.setSelectedItem(grade);
                            jTextField5.setText(login);
                            jPasswordField2.setText(mdp);
                             

                            break;  
                   case 1 : break;
                
                   
                }
        
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        
        Date d=jDateChooser2.getDate();
        java.sql.Date d1=new  java.sql.Date(d.getTime()); 
         Date da=jDateChooser1.getDate();
        java.sql.Date d2=new  java.sql.Date(da.getTime()); 
         if(jTextField13.getText().length()!=0 && jTextField14.getText().length()!=0 && d1!=null && d2!=null  && jTextField12.getText().length()!=0){
                
                Membre.creerMembre(jTextField13.getText(),jTextField14.getText(),d1,d2,jTextField12.getText());
                JOptionPane.showMessageDialog(null, "Membre enregistré");
                jTextField13.setText("");
                jTextField14.setText("");
                jDateChooser2.setDate(null);
                jDateChooser1.setDate(null);
                jTextField12.setText("");
            } 
            
            else {
                JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs SVP ");
                
            }
        
       
        
        
        
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        
        
        
         int listes = jComboBox2.getSelectedIndex();

        switch (listes)
        {
            case 0:
      
            if(jComboBox2.getSelectedItem()!=null && jTextField3.getText().length()!=0 && jPasswordField1.getText().length()!=0  )  {
                
                Utilisateur.ajoutAdmin((String) jComboBox2.getSelectedItem(),jTextField3.getText(),jPasswordField1.getText());
                JOptionPane.showMessageDialog(null, "Utilisateur crée");     
                jComboBox2.setSelectedItem("null");
                jTextField3.setText("");
                jPasswordField1.setText("");
            } 
            
            else {
                JOptionPane.showMessageDialog(null,"Veuillez remplir tous les champs SVP ");
                
            }
           
            break;
           
            case 1:
                
                 if(jComboBox2.getSelectedItem()!=null&&jTextField3.getText().length()!=0 && jPasswordField1.getText().length()!=0  )  {
                
                Utilisateur.ajoutFinancier((String) jComboBox2.getSelectedItem(),jTextField3.getText(),jPasswordField1.getText());
                JOptionPane.showMessageDialog(null, "Utilisateur crée");
                
                jComboBox2.setSelectedItem("");
                jTextField3.setText("");
                jPasswordField1.setText("");
            }
            
            else {
                JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs SVP ");
                
            }

                
            break;
        
                          
        
       
}
       
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
       
          try{
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            int ligne = jTable2.getSelectedRow();
            String table_click = (jTable2.getModel().getValueAt(ligne, 0).toString());
            
            int i = JOptionPane.showConfirmDialog(null,"Voulez-vous activer ce membre ?", "Activer", JOptionPane.YES_NO_OPTION);
            switch(i){
               case 0 :
                        //model.removeRow(ligne);
                        Membre.activerMembre(table_click);
                        JOptionPane.showMessageDialog(null, "Membre activé");
                        break;
               case 1 : break;
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e, "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        
        
        
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jTable1MouseClicked

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
        
        try{
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            int ligne = jTable2.getSelectedRow();
           
            String table_click = (jTable2.getModel().getValueAt(ligne, 0).toString());
            
            int i = JOptionPane.showConfirmDialog(null,"Voulez-vous desactiver ce membre ?", "Activer", JOptionPane.YES_NO_OPTION);
            switch(i){
               case 0 :
                        //model.removeRow(ligne);
                        Membre.desactiverMembre(table_click);
                        JOptionPane.showMessageDialog(null, "Membre desactivé");
                        break;
               case 1 : break;
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e, "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        
        
        
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
        
        
           if(jComboBox3.getSelectedItem()!=null&&jTextField5.getText().length()!=0 && jPasswordField2.getText().length()!=0 &&jTextField6.getText().length()!=0){
                //modifier admin
                Utilisateur.modifierAdmin((String) jComboBox3.getSelectedItem(),jTextField5.getText(),jPasswordField2.getText(),Integer.parseInt(jTextField6.getText()));
                JOptionPane.showMessageDialog(null, "Utilisateur mdifié");
                jComboBox2.setSelectedItem("");
                jTextField3.setText("");
                jTextField4.setText("");
                jPasswordField1.setText("");
            }else{
                JOptionPane.showMessageDialog(null, "Renseigner tous les champs");
            }
        
        
        
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables

}
