/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lesInterfacesGraphiques;

import java.awt.Color;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JOptionPane;
import lesClassesMetiers.ConsulterSms;


/**
 *
 * @author PC
 */
public class ConsulterMessage extends javax.swing.JFrame {

    /**
     * Creates new form Message
     */
    public ConsulterMessage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        location = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lenom = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        leprenom = new javax.swing.JTextField();
        naissance = new com.toedter.calendar.JDateChooser();
        dateEntree = new com.toedter.calendar.JDateChooser();

        setTitle("Consulter message");
        setLocation(new java.awt.Point(400, 50));
        setMinimumSize(new java.awt.Dimension(600, 620));
        setPreferredSize(new java.awt.Dimension(600, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Consulter message");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(210, 10, 130, 17);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 10, 530, 50);

        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Adresse :");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(70, 410, 60, 17);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane1.setViewportView(jTextArea2);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(110, 10, 410, 96);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Fermer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(330, 475, 90, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Valider");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(90, 475, 90, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Contenu :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 40, 62, 17);

        location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationActionPerformed(evt);
            }
        });
        jPanel2.add(location);
        location.setBounds(160, 400, 170, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nom :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(90, 190, 40, 17);

        lenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lelenomActionPerformed(evt);
            }
        });
        jPanel2.add(lenom);
        lenom.setBounds(160, 180, 170, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Prenom :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(70, 250, 70, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Date de Naissance :");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 310, 130, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Date d'entrée :");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(40, 360, 100, 17);

        leprenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leleprenomActionPerformed(evt);
            }
        });
        jPanel2.add(leprenom);
        leprenom.setBounds(160, 240, 170, 40);
        jPanel2.add(naissance);
        naissance.setBounds(160, 300, 170, 30);
        jPanel2.add(dateEntree);
        dateEntree.setBounds(160, 350, 170, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 60, 570, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FinancierAdmin  financiers = new FinancierAdmin();
         financiers.setVisible(true);
        this.hide();
         if (ConsulterSms.controle()==1){
        financiers.jButton16.setBackground(Color.gray);
     }else
          financiers.jButton16.setBackground(Color.green);
         
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void locationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationActionPerformed

    private void lelenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lelenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lelenomActionPerformed

    private void leleprenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leleprenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leleprenomActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here
        
        if(lenom.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Veuillez Remplir le Champ Prenom");
        }else if(leprenom.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Veuillez Remplir le Champ Prenom");
        }else if(naissance.getDate().equals("")){
            JOptionPane.showMessageDialog(this, "Veuillez Remplir le Champ Date d'Anniversaire");
        }else if( dateEntree.getDate().equals("")){
            JOptionPane.showMessageDialog(this, "Veuillez Remplir le Champ Date d'Entrée");
        }else if(location.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Veuillez Remplir le Champ Adresse");
        }else{
                String nom = lenom.getText();
                String prenom = leprenom.getText();
                String adresse = location.getText();
                 Date d=naissance.getDate();
                java.sql.Date d1=new  java.sql.Date(d.getTime()); 
                 Date da= dateEntree.getDate();
                java.sql.Date d2=new  java.sql.Date(da.getTime()); 
            ConsulterSms.consulter(nom, prenom,d1 , d2, adresse);
        }
           
    }//GEN-LAST:event_jButton2ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dateEntree;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField lenom;
    private javax.swing.JTextField leprenom;
    private javax.swing.JTextField location;
    private com.toedter.calendar.JDateChooser naissance;
    // End of variables declaration//GEN-END:variables
}
