/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lesInterfacesGraphiques;


import javax.swing.JOptionPane;  
import lesClassesMetiers.Depense;
import java.util.Date;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import lesClassesMetiers.ConsulterSms;
import lesClassesMetiers.Membre;
import lesClassesMetiers.Recette;
import lesClassesMetiers.Utilisateur;



/**
 *
 * @author PC
 */
public class FinancierAdmin extends Application {

    /**
     * Creates new form Financier
     */
    public FinancierAdmin() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * 
     * 
     */
    @SuppressWarnings("unchecked")
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton8 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel14 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jDateChooser5 = new com.toedter.calendar.JDateChooser();
        jPanel11 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jPanel19 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jDateChooser4 = new com.toedter.calendar.JDateChooser();
        jPanel20 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jDateChooser6 = new com.toedter.calendar.JDateChooser();
        jTextField7 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jButton17 = new javax.swing.JButton();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jPanel18 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jButton18 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jLabel31 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jPanel25 = new javax.swing.JPanel();
        jPanel41 = new javax.swing.JPanel();
        jPanel42 = new javax.swing.JPanel();
        jPanel43 = new javax.swing.JPanel();
        jPanel44 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable9 = new javax.swing.JTable();
        jPanel45 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTable10 = new javax.swing.JTable();
        jDateChooser7 = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jDateChooser8 = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel31 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jComboBox8 = new javax.swing.JComboBox<>();
        jLabel54 = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jPanel35 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jDateChooser11 = new com.toedter.calendar.JDateChooser();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jDateChooser12 = new com.toedter.calendar.JDateChooser();
        jLabel57 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jPanel46 = new javax.swing.JPanel();
        jPanel47 = new javax.swing.JPanel();
        jPanel48 = new javax.swing.JPanel();
        jPanel49 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTable11 = new javax.swing.JTable();
        jPanel50 = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTable12 = new javax.swing.JTable();
        jDateChooser9 = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jDateChooser10 = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jPanel26 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel30 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jDateChooser13 = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jDateChooser14 = new com.toedter.calendar.JDateChooser();
        jLabel43 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jPanel22 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel23 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setTitle("Financier");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1190, 690));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel19.setBackground(new java.awt.Color(51, 51, 255));
        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel19.setText("Gestion de flux financiers ");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(470, 0, 260, 70);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 1160, 90);

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\LPTI 3 DAR\\S5\\JAVA_EE_SOA\\lesTPJavaEE\\GestionDesFlusFinanciers\\images\\left-arrow.png")); // NOI18N
        jButton1.setText("Retour");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(10, 440, 210, 60);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\LPTI 3 DAR\\S5\\JAVA_EE_SOA\\lesTPJavaEE\\GestionDesFlusFinanciers\\images\\floppy-disk.png")); // NOI18N
        jButton2.setText("Enregistrer une recette");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(10, 30, 210, 60);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\LPTI 3 DAR\\S5\\JAVA_EE_SOA\\lesTPJavaEE\\GestionDesFlusFinanciers\\images\\save.png")); // NOI18N
        jButton3.setText("Enregistrer une dépense");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(10, 120, 210, 60);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\LPTI 3 DAR\\S5\\JAVA_EE_SOA\\lesTPJavaEE\\GestionDesFlusFinanciers\\images\\Actions-view-statistics-icon.png")); // NOI18N
        jButton4.setText("Consulter les recettes");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(10, 220, 210, 60);

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\LPTI 3 DAR\\S5\\JAVA_EE_SOA\\lesTPJavaEE\\GestionDesFlusFinanciers\\images\\Statistics-icon.png")); // NOI18N
        jButton5.setText("Consulter les dépenses");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(10, 330, 210, 60);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(8, 100, 230, 540);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new java.awt.CardLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Enregistrer une recette");
        jPanel5.add(jLabel1);
        jLabel1.setBounds(370, 20, 190, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Type de recette :");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(180, 70, 120, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Recette Principale", "Recette Secondaire" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBox2);
        jComboBox2.setBounds(340, 70, 240, 30);

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton8.setText("Valider");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton8);
        jButton8.setBounds(650, 80, 90, 30);

        jPanel4.setLayout(new java.awt.CardLayout());

        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel12.setLayout(new java.awt.CardLayout());

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Selectionnez une Catégorie :");
        jPanel9.add(jLabel4);
        jLabel4.setBounds(10, 20, 180, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Catégorie 1 ", "Catégorie 2", "Catégorie 3 ", "Catégorie 4 " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel9.add(jComboBox1);
        jComboBox1.setBounds(200, 20, 180, 30);

        jPanel10.setLayout(new java.awt.CardLayout());

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Date :");
        jPanel13.add(jLabel15);
        jLabel15.setBounds(90, 190, 40, 30);

        jButton15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton15.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\LPTI 3 DAR\\S5\\JAVA_EE_SOA\\lesTPJavaEE\\GestionDesFlusFinanciers\\images\\rechercher.png")); // NOI18N
        jButton15.setText("Rechercher");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton15);
        jButton15.setBounds(370, 10, 130, 40);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("               Membre :");
        jPanel13.add(jLabel16);
        jLabel16.setBounds(0, 30, 140, 20);
        jPanel13.add(jTextField13);
        jTextField13.setBounds(170, 20, 160, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Montant :");
        jPanel13.add(jLabel18);
        jLabel18.setBounds(70, 110, 60, 20);
        jPanel13.add(jTextField14);
        jTextField14.setBounds(170, 100, 160, 30);

        jButton16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton16.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\LPTI 3 DAR\\S5\\JAVA_EE_SOA\\lesTPJavaEE\\GestionDesFlusFinanciers\\images\\mail.png")); // NOI18N
        jButton16.setText("Consulter les messages");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton16);
        jButton16.setBounds(550, 10, 240, 40);
        jPanel13.add(jDateChooser1);
        jDateChooser1.setBounds(170, 190, 160, 30);

        jPanel10.add(jPanel13, "card2");

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Date :");
        jPanel14.add(jLabel13);
        jLabel13.setBounds(120, 100, 40, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Montant :");
        jPanel14.add(jLabel14);
        jLabel14.setBounds(100, 50, 70, 30);
        jPanel14.add(jTextField10);
        jTextField10.setBounds(190, 50, 170, 30);
        jPanel14.add(jDateChooser5);
        jDateChooser5.setBounds(190, 100, 170, 30);

        jPanel10.add(jPanel14, "card3");

        jPanel9.add(jPanel10);
        jPanel10.setBounds(20, 60, 800, 300);

        jPanel12.add(jPanel9, "card2");

        jPanel4.add(jPanel12, "card2");

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel11.setLayout(new java.awt.CardLayout());

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setLayout(null);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Membre", "Tiers" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel17.add(jComboBox3);
        jComboBox3.setBounds(210, 20, 240, 30);

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setLayout(new java.awt.CardLayout());

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setLayout(null);

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setText("Date :");
        jPanel21.add(jLabel30);
        jLabel30.setBounds(60, 160, 40, 30);

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\LPTI 3 DAR\\S5\\JAVA_EE_SOA\\lesTPJavaEE\\GestionDesFlusFinanciers\\images\\email-send-icon.png")); // NOI18N
        jButton7.setText("Envoyer un message");
        jPanel21.add(jButton7);
        jButton7.setBounds(460, 10, 181, 30);

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel34.setText("     Membre :");
        jPanel21.add(jLabel34);
        jLabel34.setBounds(20, 20, 80, 30);
        jPanel21.add(jTextField3);
        jTextField3.setBounds(120, 20, 140, 30);

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel35.setText("Montant :");
        jPanel21.add(jLabel35);
        jLabel35.setBounds(40, 90, 60, 30);
        jPanel21.add(jTextField4);
        jTextField4.setBounds(120, 90, 140, 30);

        jButton11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\LPTI 3 DAR\\S5\\JAVA_EE_SOA\\lesTPJavaEE\\GestionDesFlusFinanciers\\images\\rechercher.png")); // NOI18N
        jButton11.setText("Recherchez");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel21.add(jButton11);
        jButton11.setBounds(280, 10, 140, 30);
        jPanel21.add(jDateChooser4);
        jDateChooser4.setBounds(120, 160, 140, 30);

        jPanel19.add(jPanel21, "card3");

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setLayout(null);

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setText("Date :");
        jPanel20.add(jLabel32);
        jLabel32.setBounds(30, 230, 40, 30);

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel37.setText(" Prenom :");
        jPanel20.add(jLabel37);
        jLabel37.setBounds(10, 120, 70, 30);
        jPanel20.add(jTextField6);
        jTextField6.setBounds(110, 120, 190, 30);

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel39.setText("Montant :");
        jPanel20.add(jLabel39);
        jLabel39.setBounds(10, 180, 60, 30);
        jPanel20.add(jTextField8);
        jTextField8.setBounds(110, 180, 190, 30);

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel40.setText(" Nom :");
        jPanel20.add(jLabel40);
        jLabel40.setBounds(20, 70, 60, 30);
        jPanel20.add(jTextField9);
        jTextField9.setBounds(110, 70, 190, 30);
        jPanel20.add(jDateChooser6);
        jDateChooser6.setBounds(110, 230, 190, 30);
        jPanel20.add(jTextField7);
        jTextField7.setBounds(110, 20, 190, 30);

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel38.setText(" Libellé :");
        jPanel20.add(jLabel38);
        jLabel38.setBounds(20, 20, 50, 30);

        jPanel19.add(jPanel20, "card2");

        jPanel17.add(jPanel19);
        jPanel19.setBounds(20, 80, 830, 290);

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel36.setText("Type de Personne :");
        jPanel17.add(jLabel36);
        jLabel36.setBounds(70, 20, 120, 30);

        jPanel11.add(jPanel17, "card2");

        jPanel4.add(jPanel11, "card2");

        jPanel5.add(jPanel4);
        jPanel4.setBounds(20, 130, 880, 380);

        jPanel3.add(jPanel5, "card2");

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(null);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Type de dépenses :");
        jPanel6.add(jLabel20);
        jLabel20.setBounds(210, 70, 130, 30);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "En espèces ", "Par chèque" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jPanel6.add(jComboBox4);
        jComboBox4.setBounds(360, 70, 200, 30);

        jPanel15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel15.setLayout(new java.awt.CardLayout());

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setLayout(null);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Date de la dépense :");
        jPanel16.add(jLabel21);
        jLabel21.setBounds(30, 200, 130, 30);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Motif de la dépense :");
        jPanel16.add(jLabel22);
        jLabel22.setBounds(30, 50, 130, 30);
        jPanel16.add(jTextField16);
        jTextField16.setBounds(210, 50, 190, 30);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Montant dépensé :");
        jPanel16.add(jLabel23);
        jLabel23.setBounds(40, 130, 130, 30);
        jPanel16.add(jTextField17);
        jTextField17.setBounds(210, 130, 190, 30);

        jButton17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton17.setText("Valider");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel16.add(jButton17);
        jButton17.setBounds(381, 310, 120, 40);
        jPanel16.add(jDateChooser2);
        jDateChooser2.setBounds(210, 200, 190, 30);

        jPanel15.add(jPanel16, "card2");

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setLayout(null);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText(" Nom du bénéficiaire :");
        jPanel18.add(jLabel24);
        jLabel24.setBounds(20, 110, 140, 30);
        jPanel18.add(jTextField18);
        jTextField18.setBounds(210, 170, 170, 30);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Motif de la dépense :");
        jPanel18.add(jLabel25);
        jLabel25.setBounds(30, 170, 130, 30);
        jPanel18.add(jTextField19);
        jTextField19.setBounds(210, 230, 170, 30);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("Montant dépensé :");
        jPanel18.add(jLabel26);
        jLabel26.setBounds(40, 230, 130, 30);
        jPanel18.add(jTextField20);
        jTextField20.setBounds(210, 110, 170, 30);

        jButton18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton18.setText("Valider");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel18.add(jButton18);
        jButton18.setBounds(680, 330, 120, 40);

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Date de la dépense :");
        jPanel18.add(jLabel27);
        jLabel27.setBounds(30, 290, 130, 30);

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("Numéro du chèque :");
        jPanel18.add(jLabel28);
        jLabel28.setBounds(30, 50, 130, 30);
        jPanel18.add(jTextField22);
        jTextField22.setBounds(210, 50, 170, 30);
        jPanel18.add(jDateChooser3);
        jDateChooser3.setBounds(210, 290, 170, 30);

        jPanel15.add(jPanel18, "card2");

        jPanel6.add(jPanel15);
        jPanel15.setBounds(30, 110, 860, 400);

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel31.setText("Enregistrer une dépense");
        jPanel6.add(jLabel31);
        jLabel31.setBounds(370, 20, 190, 30);

        jPanel3.add(jPanel6, "card3");

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(null);

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel29.setText("Consulter les recettes");
        jPanel7.add(jLabel29);
        jLabel29.setBounds(370, 20, 190, 30);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Par Membre -> Recette Principale", "Par Membre -> Recette Secondaire", "Par type", "Toutes les recettes" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        jPanel7.add(jComboBox5);
        jComboBox5.setBounds(340, 70, 240, 30);

        jPanel25.setLayout(new java.awt.CardLayout());

        jPanel41.setBackground(new java.awt.Color(255, 255, 255));
        jPanel41.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel41.setLayout(new java.awt.CardLayout());

        jPanel42.setBackground(new java.awt.Color(255, 255, 255));
        jPanel42.setLayout(null);

        jPanel43.setBackground(new java.awt.Color(255, 255, 255));
        jPanel43.setLayout(new java.awt.CardLayout());

        jPanel44.setBackground(new java.awt.Color(255, 255, 255));
        jPanel44.setLayout(null);

        jTable9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nom", "Prenom", "Date", "Montant"
            }
        ));
        jTable5 = Recette.consulterRecette_secondaire_membre();
        jScrollPane9.setViewportView(jTable9);

        jPanel44.add(jScrollPane9);
        jScrollPane9.setBounds(0, 2, 830, 290);

        jPanel43.add(jPanel44, "card3");

        jPanel45.setBackground(new java.awt.Color(255, 255, 255));
        jPanel45.setLayout(null);

        jTable10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Date", "Montant Total"
            }
        ));
        jTable6 = Recette.consulterRecette_secondaire_tiers();
        jScrollPane10.setViewportView(jTable10);

        jPanel45.add(jScrollPane10);
        jScrollPane10.setBounds(2, 2, 830, 280);

        jPanel43.add(jPanel45, "card2");

        jPanel42.add(jPanel43);
        jPanel43.setBounds(20, 80, 830, 290);
        jPanel42.add(jDateChooser7);
        jDateChooser7.setBounds(480, 20, 140, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Au :");
        jPanel42.add(jLabel6);
        jLabel6.setBounds(430, 20, 40, 30);
        jPanel42.add(jTextField1);
        jTextField1.setBounds(740, 20, 120, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Total  :");
        jPanel42.add(jLabel8);
        jLabel8.setBounds(660, 20, 60, 30);
        jPanel42.add(jDateChooser8);
        jDateChooser8.setBounds(250, 20, 140, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Du :");
        jPanel42.add(jLabel9);
        jLabel9.setBounds(200, 20, 60, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Id :");
        jPanel42.add(jLabel10);
        jLabel10.setBounds(20, 20, 40, 30);
        jPanel42.add(jTextField2);
        jTextField2.setBounds(60, 20, 90, 30);

        jPanel41.add(jPanel42, "card2");

        jPanel25.add(jPanel41, "card2");

        jPanel31.setBackground(new java.awt.Color(255, 255, 255));
        jPanel31.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel31.setLayout(new java.awt.CardLayout());

        jPanel32.setBackground(new java.awt.Color(255, 255, 255));
        jPanel32.setLayout(null);

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Principale", "Secondaire" }));
        jComboBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox8ActionPerformed(evt);
            }
        });
        jPanel32.add(jComboBox8);
        jComboBox8.setBounds(150, 20, 130, 30);

        jLabel54.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel54.setText("Au :");
        jPanel32.add(jLabel54);
        jLabel54.setBounds(490, 20, 40, 30);

        jPanel33.setBackground(new java.awt.Color(255, 255, 255));
        jPanel33.setLayout(new java.awt.CardLayout());

        jPanel34.setBackground(new java.awt.Color(255, 255, 255));
        jPanel34.setLayout(null);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Montant", "Date"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        jPanel34.add(jScrollPane5);
        jScrollPane5.setBounds(10, 0, 830, 290);

        jPanel33.add(jPanel34, "card3");

        jPanel35.setBackground(new java.awt.Color(255, 255, 255));
        jPanel35.setLayout(null);

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Montant", "Date"
            }
        ));
        jScrollPane6.setViewportView(jTable6);

        jPanel35.add(jScrollPane6);
        jScrollPane6.setBounds(2, 2, 830, 280);

        jPanel33.add(jPanel35, "card2");

        jPanel32.add(jPanel33);
        jPanel33.setBounds(20, 80, 830, 290);
        jPanel32.add(jDateChooser11);
        jDateChooser11.setBounds(560, 20, 110, 30);

        jLabel55.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel55.setText("Type de Recette :");
        jPanel32.add(jLabel55);
        jLabel55.setBounds(20, 20, 120, 30);

        jLabel56.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel56.setText("Total :");
        jPanel32.add(jLabel56);
        jLabel56.setBounds(710, 20, 40, 30);
        jPanel32.add(jDateChooser12);
        jDateChooser12.setBounds(350, 20, 120, 30);

        jLabel57.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel57.setText("Du :");
        jPanel32.add(jLabel57);
        jLabel57.setBounds(310, 20, 40, 30);

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jPanel32.add(jTextField12);
        jTextField12.setBounds(760, 20, 90, 30);

        jPanel31.add(jPanel32, "card2");

        jPanel25.add(jPanel31, "card2");

        jPanel46.setBackground(new java.awt.Color(255, 255, 255));
        jPanel46.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel46.setLayout(new java.awt.CardLayout());

        jPanel47.setBackground(new java.awt.Color(255, 255, 255));
        jPanel47.setLayout(null);

        jPanel48.setBackground(new java.awt.Color(255, 255, 255));
        jPanel48.setLayout(new java.awt.CardLayout());

        jPanel49.setBackground(new java.awt.Color(255, 255, 255));
        jPanel49.setLayout(null);

        jTable11.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nom", "Prenom", "Date", "Montant"
            }
        ));
        jTable5 = Recette.consulterRecette_secondaire_membre();
        jScrollPane11.setViewportView(jTable11);

        jPanel49.add(jScrollPane11);
        jScrollPane11.setBounds(0, 2, 830, 290);

        jPanel48.add(jPanel49, "card3");

        jPanel50.setBackground(new java.awt.Color(255, 255, 255));
        jPanel50.setLayout(null);

        jTable12.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Date", "Montant Total"
            }
        ));
        jTable6 = Recette.consulterRecette_secondaire_tiers();
        jScrollPane12.setViewportView(jTable12);

        jPanel50.add(jScrollPane12);
        jScrollPane12.setBounds(2, 2, 830, 280);

        jPanel48.add(jPanel50, "card2");

        jPanel47.add(jPanel48);
        jPanel48.setBounds(20, 80, 830, 290);
        jPanel47.add(jDateChooser9);
        jDateChooser9.setBounds(480, 20, 140, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Au :");
        jPanel47.add(jLabel11);
        jLabel11.setBounds(430, 20, 40, 30);
        jPanel47.add(jTextField5);
        jTextField5.setBounds(740, 20, 120, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Total  :");
        jPanel47.add(jLabel12);
        jLabel12.setBounds(660, 20, 60, 30);
        jPanel47.add(jDateChooser10);
        jDateChooser10.setBounds(250, 20, 140, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Du :");
        jPanel47.add(jLabel17);
        jLabel17.setBounds(200, 20, 60, 30);

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel33.setText("Id :");
        jPanel47.add(jLabel33);
        jLabel33.setBounds(20, 20, 40, 30);
        jPanel47.add(jTextField11);
        jTextField11.setBounds(60, 20, 90, 30);

        jPanel46.add(jPanel47, "card2");

        jPanel25.add(jPanel46, "card2");

        jPanel26.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel26.setLayout(new java.awt.CardLayout());

        jPanel27.setBackground(new java.awt.Color(255, 255, 255));
        jPanel27.setLayout(null);

        jPanel28.setLayout(new java.awt.CardLayout());

        jPanel29.setBackground(new java.awt.Color(255, 255, 255));
        jPanel29.setLayout(null);

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Montant", "Date"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jPanel29.add(jScrollPane3);
        jScrollPane3.setBounds(0, 0, 810, 310);

        jPanel28.add(jPanel29, "card2");

        jPanel30.setBackground(new java.awt.Color(255, 255, 255));
        jPanel30.setLayout(null);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Montant", "Date"
            }
        ));
        jTable4 = Recette.consulterRecette_principaleGroupe();
        jScrollPane4.setViewportView(jTable4);

        jPanel30.add(jScrollPane4);
        jScrollPane4.setBounds(10, 20, 790, 270);

        jPanel28.add(jPanel30, "card3");

        jPanel27.add(jPanel28);
        jPanel28.setBounds(20, 60, 800, 300);
        jPanel27.add(jDateChooser13);
        jDateChooser13.setBounds(380, 10, 120, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Total :");
        jPanel27.add(jLabel7);
        jLabel7.setBounds(550, 10, 90, 30);

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel42.setText("Du :");
        jPanel27.add(jLabel42);
        jLabel42.setBounds(70, 10, 90, 30);
        jPanel27.add(jDateChooser14);
        jDateChooser14.setBounds(140, 10, 120, 30);

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel43.setText("Au :");
        jPanel27.add(jLabel43);
        jLabel43.setBounds(300, 10, 90, 30);

        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });
        jPanel27.add(jTextField15);
        jTextField15.setBounds(630, 10, 110, 30);

        jPanel26.add(jPanel27, "card2");

        jPanel25.add(jPanel26, "card2");

        jPanel7.add(jPanel25);
        jPanel25.setBounds(20, 130, 880, 380);

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton9.setText("Valider");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton9);
        jButton9.setBounds(690, 70, 90, 30);

        jPanel3.add(jPanel7, "card4");

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(null);

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel41.setText("Type de dépenses :");
        jPanel8.add(jLabel41);
        jLabel41.setBounds(210, 70, 130, 30);

        jLabel50.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel50.setText("Consulter les dépenses");
        jPanel8.add(jLabel50);
        jLabel50.setBounds(370, 20, 200, 30);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "En espèces ", "Par chèque" }));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });
        jPanel8.add(jComboBox6);
        jComboBox6.setBounds(360, 70, 200, 30);

        jPanel22.setLayout(new java.awt.CardLayout());

        jPanel24.setBackground(new java.awt.Color(255, 255, 255));
        jPanel24.setLayout(null);

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Titre 1", "Titre 2", "Titre 3", "Titre 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel24.add(jScrollPane2);
        jScrollPane2.setBounds(2, 2, 850, 230);

        jPanel22.add(jPanel24, "card2");

        jPanel23.setBackground(new java.awt.Color(255, 255, 255));
        jPanel23.setLayout(null);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Titre 1", "Titre 2", "Titre 3", "Titre 4", "Titre 5", "Titre 6"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel23.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 860, 230);

        jPanel22.add(jPanel23, "card2");

        jPanel8.add(jPanel22);
        jPanel22.setBounds(30, 110, 860, 400);

        jPanel3.add(jPanel8, "card5");

        getContentPane().add(jPanel3);
        jPanel3.setBounds(250, 110, 920, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(jPanel7);
        jPanel3.repaint();
        jPanel3.revalidate();
        
        
  
           
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(jPanel6);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(jPanel5);
        jPanel3.repaint();
        jPanel3.revalidate();
       
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Administrateur admin = new Administrateur();
       admin.setVisible(true);  
      this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(jPanel8);
        jPanel3.repaint();
        jPanel3.revalidate();
        

                
             DefaultTableModel dftm=new javax.swing.table.DefaultTableModel(
            new Object [][] {
                 
            },
            new String [] {
                "N° ", "Motif", "Montant", "Date"
            }
        );
         
         dftm = Depense.consulterDepenseEspese(dftm);
         jTable2.setModel(dftm); 
  
            DefaultTableModel dftml=new javax.swing.table.DefaultTableModel(
            new Object [][] {          
                 
            },
            new String [] {
                "N° ", "N° du Chèque", "Nom du bénéficiaire", "Motif","Montant","Date"
            }
        );
   
         dftml = Depense.consulterDepenseCheque(dftml);
         jTable1.setModel(dftml);           

         
                 
            

    
                   
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
         int listes = jComboBox2.getSelectedIndex();

				switch (listes)
				{ 
				  case 0:
                                      
                                         jPanel4.removeAll();
                                         jPanel4.repaint();
                                         jPanel4.revalidate();

                                         jPanel4.add(jPanel12);
                                         jPanel4.repaint();
                                         jPanel4.revalidate();
                                 break;
				 case 1:
                                      
                                         jPanel4.removeAll();
                                         jPanel4.repaint();
                                         jPanel4.revalidate();

                                         jPanel4.add(jPanel11);
                                         jPanel4.repaint();
                                         jPanel4.revalidate();
                                         
                                 break;
                                }   
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
        int list = jComboBox4.getSelectedIndex();

				switch (list)
				{ 
                                    case 0:
                                      
                                         jPanel15.removeAll();
                                         jPanel15.repaint();
                                         jPanel15.revalidate();

                                         jPanel15.add(jPanel16);
                                         jPanel15.repaint();
                                         jPanel15.revalidate();
                                  break;
                                    
                                    case 1:
                                      
                                        
                                         jPanel15.removeAll();
                                         jPanel15.repaint();
                                         jPanel15.revalidate();

                                         jPanel15.add(jPanel18);
                                         jPanel15.repaint();
                                         jPanel15.revalidate();
                                  break;
                                
                                }   
        
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
        int list = jComboBox6.getSelectedIndex();

				switch (list)
				{ 
                                    case 0:
                                      
                                         jPanel22.removeAll();
                                         jPanel22.repaint();
                                         jPanel22.revalidate();

                                         jPanel22.add(jPanel24);
                                         jPanel22.repaint();
                                         jPanel22.revalidate();
                                  break;
                                    
                                    case 1:
                                      
                                        
                                         jPanel22.removeAll();
                                         jPanel22.repaint();
                                         jPanel22.revalidate();

                                         jPanel22.add(jPanel23);
                                         jPanel22.repaint();
                                         jPanel22.revalidate();
                                  break;
                                
                                }   
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        
       ConsulterMessage mess = new ConsulterMessage();
        mess.setVisible(true); 
        ConsulterMessage.jTextArea2.setText(ConsulterSms.texte());
       this.hide();
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        int list = jComboBox1.getSelectedIndex();

        switch (list)
        {
            case 0:

            jPanel10.removeAll();
            jPanel10.repaint();
            jPanel10.revalidate();

            jPanel10.add(jPanel13);
            jPanel10.repaint();
            jPanel10.revalidate();
            break;

            case 1:

            jPanel10.removeAll();
            jPanel10.repaint();
            jPanel10.revalidate();

            jPanel10.add(jPanel13);
            jPanel10.repaint();
            jPanel10.revalidate();
            break;
            case 2:

            jPanel10.removeAll();
            jPanel10.repaint();
            jPanel10.revalidate();

            jPanel10.add(jPanel13);
            jPanel10.repaint();
            jPanel10.revalidate();
            break;
            case 3:

            jPanel10.removeAll();
            jPanel10.repaint();
            jPanel10.revalidate();

            jPanel10.add(jPanel14);
            jPanel10.repaint();
            jPanel10.revalidate();
            break;
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
        int list = jComboBox3.getSelectedIndex();

				switch (list)
				{ 
                                    case 0:
                                      
                                         jPanel19.removeAll();
                                         jPanel19.repaint();
                                         jPanel19.revalidate();

                                         jPanel19.add(jPanel21);
                                         jPanel19.repaint();
                                         jPanel19.revalidate();
                                  break;
                                    
                                    case 1:
                                      
                                        
                                         jPanel19.removeAll();
                                         jPanel19.repaint();
                                         jPanel19.revalidate();

                                         jPanel19.add(jPanel20);
                                         jPanel19.repaint();
                                         jPanel19.revalidate();
                                  break;
                                
                                }   
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here: 
         Date day=jDateChooser2.getDate();
         java.sql.Date d6= new java.sql.Date(day.getTime());
        
        
        
         int list = jComboBox4.getSelectedIndex();

                switch (list)
                             { 
                      case 0:
                                      
                                        
             
         if(jTextField16.getText().length()!=0 && jTextField17.getText().length()!=0 && d6!=null){
                
                Depense.enregistrerDepenseEspece(jTextField16.getText(),Float.parseFloat(jTextField17.getText().trim()),d6);
                JOptionPane.showMessageDialog(null, "Dépense enregistré");
                jTextField16.setText("");
                jTextField17.setText("");
                jDateChooser2.setDate(null);
                
            } 
            
            else {
                JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs SVP ");
                
            }
                   
                                        
               break;
                }    
        
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        
       
         int list = jComboBox4.getSelectedIndex();

                switch (list)
                             {
               
               case 1:
                                        
                                        
           if(jTextField22.getText().length()!=0 &&  jTextField20.getText().length()!=0 &&  jTextField18.getText().length()!=0 && jTextField19.getText().length()!=0 && jDateChooser3.getDate()!=null ){
                 Date day=jDateChooser3.getDate();
                 java.sql.Date d3= new java.sql.Date(day.getTime());
                 Depense.enregistrerDepenseCheque(Integer.parseInt(jTextField22.getText()),jTextField20.getText(), jTextField18.getText(), Float.parseFloat(jTextField19.getText().trim()),d3);
                JOptionPane.showMessageDialog(null, "Dépense enregistré");
                jTextField22.setText("");
                jTextField20.setText("");
                jTextField18.setText("");
                jTextField19.setText("");
                jDateChooser2.setDate(null);
                
            } else {
                JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs SVP ");
                
            }break;
                                
            }    
  
                          
        
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here
        
	  Date d=jDateChooser1.getDate();
        java.sql.Date d1= new java.sql.Date(d.getTime());
        
         Date da=jDateChooser5.getDate();
        java.sql.Date d5= new java.sql.Date(da.getTime());
        
        
	  if(jComboBox2.getSelectedIndex()==0) {
            
            int list = jComboBox1.getSelectedIndex();

    switch (list)
        { 
                    
                          case 0:
                                        
                                        
           if(jTextField13.getText().length()!=0 && jTextField14.getText().length()!=0 &&  d1!=null ){
                 if(Recette.recherche(jTextField13.getText())==1){
                Recette.enregistrerRecette_principale(Integer.parseInt(jTextField13.getText()), Float.parseFloat(jTextField14.getText().trim()),d1);
                JOptionPane.showMessageDialog(null, "Récette enregistré");
                 }else{JOptionPane.showMessageDialog(null, "Envoyez un message à l'administrateur,le membre que vous aviez saisi n'existe pas");}
                jTextField13.setText("");
                jTextField14.setText("");
                jDateChooser1.setDate(null);
                
            } 
            
            else {
                JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs SVP ");
                
            }
                       
                                        
                      break;
                      
                      
                      case 1:
                                        
                                        
           if(jTextField13.getText().length()!=0 && jTextField14.getText().length()!=0 &&  d1!=null ){
                if(Recette.recherche(jTextField13.getText())==1){
                Recette.enregistrerRecette_principale(Integer.parseInt(jTextField13.getText()), Float.parseFloat(jTextField14.getText().trim()),d1);
                 JOptionPane.showMessageDialog(null, "Récette enregistré");
                }else {JOptionPane.showMessageDialog(null, "Envoyez un message à l'administrateur le membre que vous aviez saisi n'existe pas");}
               
                jTextField13.setText("");
                jTextField14.setText("");
                jDateChooser1.setDate(null);
                
            } 
            
            else {
                JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs SVP ");
                
            }
                       
                                        
                      break;
                      
                      
                      case 2:
                                        
                                        
           if(jTextField13.getText().length()!=0 && jTextField14.getText().length()!=0 &&  d1!=null ){
                if(Recette.recherche(jTextField13.getText())==1){
                Recette.enregistrerRecette_principale(Integer.parseInt(jTextField13.getText()), Float.parseFloat(jTextField14.getText().trim()),d1);
                JOptionPane.showMessageDialog(null, "Récette enregistré"); 
                }else {JOptionPane.showMessageDialog(null, "Envoyez un message à l'administrateur le membre que vous aviez saisi n'existe pas");}
                jTextField13.setText("");
                jTextField14.setText("");
                jDateChooser1.setDate(null);
                
            } 
            
            else {
                JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs SVP ");
                
            }
                       
                                        
                      break;
                      
                      
                      case 3:
                                        
                                        
           if(jTextField10.getText().length()!=0 && d5!=null ){
                Recette.enregistrerRecette_principaleGroupe(Float.parseFloat(jTextField10.getText().trim()),d5);
                JOptionPane.showMessageDialog(null, "Récette enregistré");  
                   
                jTextField10.setText("");
                jDateChooser5.setDate(null);
                
            } 
            
            else {
                JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs SVP ");
                
            }
                       
                                        
                      break;
                                
            }    
            
            
            
  
  }else if(jComboBox2.getSelectedIndex()==1) {
            
             Date date=jDateChooser1.getDate();
        java.sql.Date d4= new java.sql.Date(date.getTime());
        
             int list = jComboBox3.getSelectedIndex();

    switch (list)
        { 
                    
                case 0:
                                        
                                        
           if(jTextField3.getText().length()!=0 && jTextField4.getText().length()!=0 &&  d4!=null ){
                 if(Recette.recherche(jTextField13.getText())==1){
                Recette.enregistrerRecette_secondaire_membre(Integer.parseInt(jTextField3.getText()), Float.parseFloat(jTextField4.getText().trim()),d4);
                JOptionPane.showMessageDialog(null, "Récette enregistré");
                 }else {JOptionPane.showMessageDialog(null, "Envoyez un message à l'administrateurn le membre que vous aviez saisi n'existe pas");}
                jTextField3.setText("");
                jTextField4.setText("");
                jDateChooser4.setDate(null);
                
            } 
            
            else {
                JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs SVP ");
                
            }
                       
                                        
                      break;
                      
                      
          case 1:
                                        
                Date day=jDateChooser6.getDate();
                java.sql.Date d6= new java.sql.Date(day.getTime());
                                   
           if(jTextField7.getText().length()!=0 && jTextField9.getText().length()!=0 && jTextField6.getText().length()!=0 && jTextField8.getText().length()!=0 &&  d6!=null ){
                
                Recette.enregistrerRecette_secondaire_tiers(jTextField7.getText(),jTextField9.getText(),jTextField6.getText() ,Float.parseFloat(jTextField8.getText().trim()),d6);
                JOptionPane.showMessageDialog(null, "Récette enregistré");
                jTextField7.setText("");
                jTextField9.setText("");
                jTextField6.setText("");
                jTextField8.setText("");
                jDateChooser6.setDate(null);
                
            } 
            
            else {
                JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs SVP ");
                
            }
                       
                                        
                      break;
                      
                   
                }
            
  
            }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
        
        int list = jComboBox5.getSelectedIndex();

				switch (list)
				{ 
                                    case 0:
                                      
                                         jPanel25.removeAll();
                                         jPanel25.repaint();
                                         jPanel25.revalidate();

                                         jPanel25.add(jPanel42);
                                         jPanel25.repaint();
                                         jPanel25.revalidate();
                                  break;
                                  
                                  case 1:
                                      
                                         jPanel25.removeAll();
                                         jPanel25.repaint();
                                         jPanel25.revalidate();

                                         jPanel25.add(jPanel46);
                                         jPanel25.repaint();
                                         jPanel25.revalidate();
                                  break;
                                    
                                    case 2:
                                      
                                        
                                         jPanel25.removeAll();
                                         jPanel25.repaint();
                                         jPanel25.revalidate();

                                         jPanel25.add(jPanel31);
                                         jPanel25.repaint();
                                         jPanel25.revalidate();
                                  break;
                                  
                             
                                  
                                  case 3:
                                      
                                        
                                         jPanel25.removeAll();
                                         jPanel25.repaint();
                                         jPanel25.revalidate();

                                         jPanel25.add(jPanel26);
                                         jPanel25.repaint();
                                         jPanel25.revalidate();
                                  break;
                                
                                }   
        
        
       
        
        
        
        
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        
         if(jComboBox2.getSelectedIndex()==0) {
            
            int list = jComboBox1.getSelectedIndex();

    switch (list)
        { 
                    
                          case 0:
                                        
                String name= jTextField13.getText();                       
           if(name.length()!=0){
               Recette.rechercherMembre(name);
               if(Recette.recherche(name)==1){
                   
                    JOptionPane.showMessageDialog(null, "Membre trouvé");
               }
               else 
                   if(Recette.recherche(name)==0){
                       JOptionPane.showMessageDialog(null, "Membre non trouvé");
                       
                   
               }
               
                       
             
            } 
            
            else {
                JOptionPane.showMessageDialog(null, "\"Veuillez remplir le champ nom SVP");
                
            }
                       
                                        
                      break;
                      
                      
                      case 1:
                                        
                                        
           String name1= jTextField13.getText();                       
           if(name1.length()!=0){
               Recette.rechercherMembre(name1);
               if(Recette.recherche(name1)==1){
                   
                    JOptionPane.showMessageDialog(null, "Membre trouvé");
               }
               else 
                   if(Recette.recherche(name1)==0){
                       JOptionPane.showMessageDialog(null, "Membre non trouvé");
                       
                   
               }
        
                
            } 
            
            else {
                JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs SVP ");
                
            }
                       
                                        
                      break;
                      
                      
                      case 2:
                                        
                                        
          String name2= jTextField13.getText();                       
           if(name2.length()!=0){
               Recette.rechercherMembre(name2);
               if(Recette.recherche(name2)==1){
                   
                    JOptionPane.showMessageDialog(null, "Membre trouvé");
               }
               else 
                   if(Recette.recherche(name2)==0){
                       JOptionPane.showMessageDialog(null, "Membre desactivé");
                       
                   
               }          
                
                
            } 
            
            else {
                JOptionPane.showMessageDialog(null, "Veuillez remplir le champ nom SVP ");
                
            }
                       
                                        
                      break;
                      
                      
                      
                                
            }    
            
            
            
  
  }else if(jComboBox2.getSelectedIndex()==1) {
            
            
             int list = jComboBox3.getSelectedIndex();

    switch (list)
        { 
                    
                case 0:
                                        
                                        
           String name= jTextField13.getText();                       
           if(name.length()!=0){
               Recette.rechercherMembre(name);
               if(Recette.recherche(name)==1){
                   
                    JOptionPane.showMessageDialog(null, "Membre trouvé");
               }
               else 
                   if(Recette.recherche(name)==0){
                       JOptionPane.showMessageDialog(null, "Membre desactivé");
                       
                   
               }
            
                
            } 
            
            else {
                JOptionPane.showMessageDialog(null, "Veuillez remplir le champ nom SVP");
                
            }
                       
                                        
                      break;
                      
                   
                }
            
  
  }
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        
        if(jComboBox2.getSelectedIndex()==0) {
            
            int list = jComboBox1.getSelectedIndex();

    switch (list)
        { 
                    
                          case 0:
                                        
                String name= jTextField13.getText();                       
           if(name.length()!=0){
               Recette.rechercherMembre(name);
               if(Recette.recherche(name)==1){
                   
                    JOptionPane.showMessageDialog(null, "Membre trouvé");
               }
               else 
                   if(Recette.recherche(name)==0){
                       JOptionPane.showMessageDialog(null, "Membre non trouvé");
                       
                   
               }
               
                       
             
            } 
            
            else {
                JOptionPane.showMessageDialog(null, "\"Veuillez remplir le champ nom SVP");
                
            }
                       
                                        
                      break;
                      
                      
                      case 1:
                                        
                                        
           String name1= jTextField13.getText();                       
           if(name1.length()!=0){
               Recette.rechercherMembre(name1);
               if(Recette.recherche(name1)==1){
                   
                    JOptionPane.showMessageDialog(null, "Membre trouvé");
               }
               else 
                   if(Recette.recherche(name1)==0){
                       JOptionPane.showMessageDialog(null, "Membre non trouvé");
                       
                   
               }
        
                
            } 
            
            else {
                JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs SVP ");
                
            }
                       
                                        
                      break;
                      
                      
                      case 2:
                                        
                                        
          String name2= jTextField13.getText();                       
           if(name2.length()!=0){
               Recette.rechercherMembre(name2);
               if(Recette.recherche(name2)==1){
                   
                    JOptionPane.showMessageDialog(null, "Membre trouvé");
               }
               else 
                   if(Recette.recherche(name2)==0){
                       JOptionPane.showMessageDialog(null, "Membre non trouvé");
                       
                   
               }          
                
                
            } 
            
            else {
                JOptionPane.showMessageDialog(null, "Veuillez remplir le champ nom SVP ");
                
            }
                       
                                        
                      break;
                      
                      
                      
                                
            }    
            
            
            
  
  }else if(jComboBox2.getSelectedIndex()==1) {
            
            
             int list = jComboBox3.getSelectedIndex();

    switch (list)
        { 
                    
                case 0:
                                        
                                        
           String name= jTextField13.getText();                       
           if(name.length()!=0){
               Recette.rechercherMembre(name);
               if(Recette.recherche(name)==1){
                   
                    JOptionPane.showMessageDialog(null, "Membre trouvé");
               }
               else 
                   if(Recette.recherche(name)==0){
                       JOptionPane.showMessageDialog(null, "Membre non trouvé");
                       
                   
               }
            
                
            } 
            
            else {
                JOptionPane.showMessageDialog(null, "Veuillez remplir le champ nom SVP");
                
            }
                       
                                        
                      break;
                      
                   
                }
   
  }
       
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        
        
        
        
                                         jPanel43.removeAll();
                                         jPanel43.repaint();
                                         jPanel43.revalidate();

                                         jPanel43.add(jPanel44);
                                         jPanel43.repaint();
                                         jPanel43.revalidate();
                
                 
          
             int list = jComboBox5.getSelectedIndex();

				switch (list)
				{ 
                                    case 0:
                                      
           DefaultTableModel dftm=new javax.swing.table.DefaultTableModel(
            new Object [][] {
                 
            },
            new String [] {
                "id ","Nom","Prenom", "Date", "Montant"
            }
        );
         
     
         
                                         
     if(jTextField2.getText().length()!=0 && jDateChooser8.getDate()!=null && jDateChooser7.getDate()!=null ){
         String id = jTextField2.getText();
         Date db = jDateChooser8.getDate();
         java.sql.Date d1 = new java.sql.Date(db.getTime());
         Date df = jDateChooser7.getDate();
         java.sql.Date d2 = new java.sql.Date(df.getTime());
                  dftm = Recette.consulterRecetteP(dftm,id,d1.toString(), d2.toString());
                  
                jTable9.setModel(dftm);  
                jTextField1.setText(Recette.CalculMontantRecettePMembre(id,d1.toString(),d2.toString()));   
                jTextField2.setText("");
                jDateChooser8.setDate(null);
                jDateChooser7.setDate(null);
                
            } 
            
            else {
                JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs SVP ");
                
            } 
                 
                                  break;
                                  
                                  case 1:
                                      
         DefaultTableModel dftm1 =new javax.swing.table.DefaultTableModel(
            new Object [][] {
                 
            },
            new String [] {
                "id ","Nom","Prenom", "Date", "Montant"
            }
        );
         
     
         
                                         
     if(jTextField2.getText().length()!=0 && jDateChooser8.getDate()!=null && jDateChooser7.getDate()!=null ){
         String id = jTextField2.getText();
         Date db = jDateChooser8.getDate();
         java.sql.Date d1 = new java.sql.Date(db.getTime());
         Date df = jDateChooser7.getDate();
         java.sql.Date d2 = new java.sql.Date(df.getTime());
                  dftm = Recette.consulterRecetteS(dftm1,id,d1.toString(), d2.toString());
                  
                jTable10.setModel(dftm);  
                jTextField1.setText(Recette.CalculMontantRecetteSMembre(id,d1.toString(),d2.toString()));   
                jTextField2.setText("");
                jDateChooser8.setDate(null);
                jDateChooser7.setDate(null);
                
            } 
            
            else {
                JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs SVP ");
                
            } 
                                      
                                 
                                      
                                      
                                  break;
                                    
                   case 2:
                                      
               DefaultTableModel dftm2 =new javax.swing.table.DefaultTableModel(
            new Object [][] {
                 
            },
            new String [] {
                "Id ","Montant","Date"
            }
        );
         
     
         if(jComboBox8.getSelectedIndex()==0) {
                  
                                        
          if(jDateChooser12.getDate()!=null && jDateChooser11.getDate()!=null ){
         Date db = jDateChooser12.getDate();
         java.sql.Date d1 = new java.sql.Date(db.getTime());
         Date df = jDateChooser11.getDate();
         java.sql.Date d2 = new java.sql.Date(df.getTime());
         dftm = Recette.consulterTotalRecettep(dftm2,d1.toString(), d2.toString());
                  
                jTable5.setModel(dftm);  
                jTextField12.setText(Recette.CalculMontantRecetteP(d1.toString(),d2.toString()));
                jDateChooser12.setDate(null);
                jDateChooser11.setDate(null);
                
            } 
            
            else {
                JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs SVP ");
                
            } 
 
         
   }else if (jComboBox8.getSelectedIndex()==1){
       
       
                if(jDateChooser12.getDate()!=null && jDateChooser11.getDate()!=null ){
         Date db = jDateChooser12.getDate();
         java.sql.Date d1 = new java.sql.Date(db.getTime());
         Date df = jDateChooser11.getDate();
         java.sql.Date d2 = new java.sql.Date(df.getTime());
         dftm = Recette.consulterTotalRecetteS(dftm2,d1.toString(), d2.toString());
                  
                jTable6.setModel(dftm);  
                jTextField12.setText(Recette.CalculMontantRecetteS(d1.toString(),d2.toString()));
                jDateChooser12.setDate(null);
                jDateChooser11.setDate(null);
                
            } 
            
            else {
                JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs SVP ");
                
            } 
       
       
                       
                   }
                                         
                             case 3:
                                 
            DefaultTableModel dftm3=new javax.swing.table.DefaultTableModel(
            new Object [][] {
                 
            },
            new String [] {
                 "Montant", "Date"
            }
        );
         
     
         
                                         
     if(jDateChooser14.getDate()!=null && jDateChooser13.getDate()!=null){
         Date db = jDateChooser14.getDate();
         java.sql.Date d1 = new java.sql.Date(db.getTime());
         Date df = jDateChooser13.getDate();
         java.sql.Date d2 = new java.sql.Date(df.getTime());
         
                  dftm = Recette.consulterTotalRecette(dftm3,d1.toString(),d2.toString());
                  
                jTable3.setModel(dftm);  
                 jTextField15.setText(Recette.CalculMontantTotal(d1.toString(),d2.toString())); 
               
                jDateChooser14.setDate(null);
                jDateChooser13.setDate(null);
             
                
            } 
            
            else {
                JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs SVP ");
                
            } 
                 
                                  break;
                       
                                
                                }   
        
        
        
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jComboBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox8ActionPerformed
        // TODO add your handling code here:

        int list = jComboBox8.getSelectedIndex();

        switch (list)
        {
            case 0:

            jPanel33.removeAll();
            jPanel33.repaint();
            jPanel33.revalidate();

            jPanel33.add(jPanel34);
            jPanel33.repaint();
            jPanel33.revalidate();
            break;

            case 1:

            jPanel33.removeAll();
            jPanel33.repaint();
            jPanel33.revalidate();

            jPanel33.add(jPanel35);
            jPanel33.repaint();
            jPanel33.revalidate();
            break;

        }

    }//GEN-LAST:event_jComboBox8ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton15;
    public static javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox8;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser10;
    private com.toedter.calendar.JDateChooser jDateChooser11;
    private com.toedter.calendar.JDateChooser jDateChooser12;
    private com.toedter.calendar.JDateChooser jDateChooser13;
    private com.toedter.calendar.JDateChooser jDateChooser14;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private com.toedter.calendar.JDateChooser jDateChooser4;
    private com.toedter.calendar.JDateChooser jDateChooser5;
    private com.toedter.calendar.JDateChooser jDateChooser6;
    private com.toedter.calendar.JDateChooser jDateChooser7;
    private com.toedter.calendar.JDateChooser jDateChooser8;
    private com.toedter.calendar.JDateChooser jDateChooser9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable10;
    private javax.swing.JTable jTable11;
    private javax.swing.JTable jTable12;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
